
### ceckin
POST http://localhost:5000/api/pemesanan
Content-Type: application/json
Authorization: b970b5a5-ce63-4bae-ba72-a99220af811b

{
  "id_ruangan": 6,
  "nama": "mr. frandi",
  "durasi_menit": 120
}


### preview
GET  http://localhost:5000/api/pemesanan/preview/11
Content-Type: application/json
Authorization: ee596d5b-27a7-4061-b8ee-b8bbc6a312ea

### get by status
GET  http://localhost:5000/api/pemesanan
Content-Type: application/json
Authorization: b970b5a5-ce63-4bae-ba72-a99220af811b




### pesan fnb
POST http://localhost:5000/api/pemesanan/11/fnb
Content-Type: application/json
Authorization: ee596d5b-27a7-4061-b8ee-b8bbc6a312ea

{
  "id_menu_fnb": 4,
  "jumlah": 4,
  "id_user": 1
}

### pesan fnb preview
GET  http://localhost:5000/api/pemesanan/11/fnb/preview
Content-Type: application/json
Authorization: ee596d5b-27a7-4061-b8ee-b8bbc6a312ea


### update pesanan fnb /pemesanan/:id_user/fnb/:id_detail
PATCH http://localhost:5000/api/pemesanan/1/fnb/12
Content-Type: application/json
Authorization: ee596d5b-27a7-4061-b8ee-b8bbc6a312ea

{
  "jumlah": 10
}


### delete pesanan fnb /pemesanan/:id_detail/fnb
DELETE http://localhost:5000/api/pemesanan/9/fnb
Content-Type: application/json
Authorization: ee596d5b-27a7-4061-b8ee-b8bbc6a312ea


### ceckout
POST http://localhost:5000/api/pemesanan/ceckout
Content-Type: application/json
Authorization: ee596d5b-27a7-4061-b8ee-b8bbc6a312ea

{
  "id": 11,
  "id_user": 1,
  "durasi_dipesan_menit": 60,
  "total_sewa": 20000,
  "total_fnb": 40000,
  "total_tagihan": 60000,
  "metode_pembayaran" : "tunai",
  "jumlah_bayar": 100000,
  "catatan": "test catatan"
}