### create user
POST http://localhost:5000/api/users 
Content-Type: application/json
Authorization: 7eee4f3a-f580-4a00-91c5-504df6b2bb64

{
  "username": "kasir",
  "nama": "kasir",
  "password": "kasir",
  "role": "kasir"
}

### login user
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### get user by username
GET http://localhost:5000/api/users/profile
Content-Type: application/json
Authorization: 55041b4a-bcce-4f0c-af96-c29cd297ebb1

### updata user
PATCH  http://localhost:5000/api/users/admin
Content-Type: application/json
Authorization: 81dc720a-abd2-42fa-a083-c0673068d45a

{
  "nama": "admin"
}

### logout user
DELETE  http://localhost:5000/api/users/logout
Content-Type: application/json
Authorization: ae5de44b-bf8c-4031-a41b-daeebc3b5dee


### get all user kusus admin
GET  http://localhost:5000/api/users
Content-Type: application/json
Authorization: 12db5b84-f522-42df-99e0-be83d05e7189

