### create user
POST http://localhost:5000/api/users 
Content-Type: application/json

{
  "username": "kasir",
  "nama": "kasir",
  "password": "kasir",
  "role": "kasir"
}

### login user
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### get user by username
GET http://localhost:5000/api/users/admin
Content-Type: application/json
Authorization: token f1b38087-0c90-405d-82e2-520fa4605a39