### create user
POST http://localhost:5000/api/users 
Content-Type: application/json

{
  "username": "kasir",
  "nama": "kasir",
  "password": "kasir",
  "role": "kasir"
}

### login user
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### get user by username
GET http://localhost:5000/api/users/profile
Content-Type: application/json
Authorization: ae5de44b-bf8c-4031-a41b-daeebc3b5dee


### updata user
PATCH  http://localhost:5000/api/users/admin
Content-Type: application/json
Authorization: 81dc720a-abd2-42fa-a083-c0673068d45a

{
  "nama": "admin"
}

### logout user
DELETE  http://localhost:5000/api/users/logout
Content-Type: application/json
Authorization: ae5de44b-bf8c-4031-a41b-daeebc3b5dee

